### ISSUE TITLE
Please help me fix this!

### ISSUE THREAD

**Issue by AlemPROO** [SouprP/Banker#1]
How do I fix this issue with the bank, I have connected it to mysql database but when someone deposits money into the bank when they try to withdraw it, it says they have 0 balance???

**Comment by SouprP** [comment]
Please, tell me what version of the plugin you are using, and are you sure you have an economy plugin on your server?
There's a possibility that you are using an older version than v1.2.1 where I fixed a bug with a deposit, where money wasnt deposited at all, but it took your money anyway.

**Comment by AlemPROO** [comment]
I downloaded the latest version today is my first time downloading it too. I just have essentials on my server so that is my economy plugin. My version is v1.2.1

**Comment by AlemPROO** [comment]
Do you have any kind of command or a setting where you can like turn on advanced inspection so everything would show up in chat or console if not I am putting that as a suggestion so you can help people faster and better.

**Comment by AlemPROO** [comment]
Like show everything the plugin interacts with or do.

**Comment by SouprP** [comment]
There isnt anything like advanced inspection yet. Althought i can add it in the next update.

**Comment by SouprP** [comment]
I implemented it into the plugin.
![Console](https://user-images.githubusercontent.com/67385974/124524867-1db81600-ddfd-11eb-8713-e79d78426528.png)

**Comment by AlemPROO** [comment]
So how can I download that so you can see the issue?

**Comment by SouprP** [comment]
v1.3 pre-release 1 just dropped

**Comment by AlemPROO** [comment]
Ok thanks.

**Comment by SouprP** [comment]
Anything changed?

**Comment by AlemPROO** [comment]
I am not sure I wasn't able to download it in time because I am on a vacation.
