### ISSUE TITLE
What do I put for the database?

### ISSUE THREAD

**Issue by AlemPROO** [SouprP/Banker#2]
What do I put for the database? I have filled it out for host, port, username and password but what do I put for database? I use MySQL database so do I write mysql? I tried to write mysql but it didn't work. When I try to use /banker it says Yu can't use this command because the plugin is not connected to a database!

**Comment by SouprP** [comment]
You need to pass in a database name / SCHEMA name. It's bassicly one of these things ( MySQL Workbench ).
![MYSQL SCHEMA](https://user-images.githubusercontent.com/67385974/126908600-e4cf0065-3493-4847-9552-d332a10b747e.png)

**Comment by SouprP** [comment]
This is how it looks like in my case
![how it looks like](https://user-images.githubusercontent.com/67385974/126909045-234f4e35-115a-406f-bb2f-2855a59227f4.png)

**Comment by AlemPROO** [comment]
Yeah I cannot curently try it because I have some form of a problem logging into mysql I can post the line of code here.

**Comment by AlemPROO** [comment]
mysqli_real_connect(): (HY000/1045): Access denied for user 'MYUSERNAME'

**Comment by SouprP** [comment]
I don't know what could be wrong with that, are you sure you put everything correctly? (That's my guess ) Maybe look for some possible fixes on yt or google?

**Comment by AlemPROO** [comment]
I am restarting my server I was able to fix that problem and put in the database I will try now to use the command once my server restarts.

**Comment by AlemPROO** [comment]
Everything works now, thanks. And the past issue with depositing and not having the cash on their account has been fixed. Thank you very much!
