### ISSUE TITLE
Banker disappears, but still exists, seem to reappear when relogging, no error logs, running PaperMC with modded settings for performance

### ISSUE THREAD

**Issue by Manic137** [SouprP/Banker#3]

**Comment by SouprP** [comment]
Right now im not home, but I'm gonna look into that

**Comment by SouprP** [comment]
Are there any errors in the console?

**Comment by Manic137** [comment]
> Are there any errors in the console?

There are non

**Comment by SouprP** [comment]
So, what version of PaperMC were you using? I tried running Banker v1.3.1 on 1.17 #79 and everything seemed to be working fine.

**Comment by Manic137** [comment]
> So, what version of PaperMC were you using? I tried running Banker v1.3.1 on 1.17 #79 and everything seemed to be working fine.

1.17.1, can't recall build, but the problem comes and goes. Takes a while, almost random
