### ISSUE TITLE
Plugin doesn't detect EconomyPlus

### ISSUE THREAD

**Issue by Manic137** [SouprP/Banker#5]
I've been trying to fix the issue for a few days now, I am in contact with EconomyPlus(https://www.spigotmc.org/resources/economyplus.92975/) devs and we thought we fixed it. We found that the plugin was launching before economy, and thus, wasn't detecting the economy, this was proven with a Plugman plugin and reloading the Banker plugin after the server loaded, and proves to fix the issue temporarily, The devs then proceeded to fix the problem through an update, but it still seems to not be fixed for me. Do you have any idea what I could do?

[Logs.txt](https://github.com/SouprP/Banker/files/6951678/Logs.txt)

**Comment by SouprP** [comment]
I will just add the economy plugin you are using as a softdepend in plugin.yml. That probably will fix the issue.

**Comment by SouprP** [comment]
I tested it and the fix works just as intented. You can download the newest version of Banker to get rid of this issue. Closing the issue.
